// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbzwjOq8kGTJPPSkrLxtF8dXP92IvNtcU',
    appId: '1:794333114909:web:3999726cf0642f2c774cf4',
    messagingSenderId: '794333114909',
    projectId: 'travel-passport-5cefb',
    authDomain: 'travel-passport-5cefb.firebaseapp.com',
    storageBucket: 'travel-passport-5cefb.firebasestorage.app',
    measurementId: 'G-HFVJ9XBJ62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9bg_jVnuE-lA09AEb76rjayuRRYn9ugk',
    appId: '1:794333114909:android:62a9b5596ca0acfe774cf4',
    messagingSenderId: '794333114909',
    projectId: 'travel-passport-5cefb',
    storageBucket: 'travel-passport-5cefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn-P55fEdwMg1uIasckywdS9MA8AJfdPM',
    appId: '1:794333114909:ios:2d43790a95640b57774cf4',
    messagingSenderId: '794333114909',
    projectId: 'travel-passport-5cefb',
    storageBucket: 'travel-passport-5cefb.firebasestorage.app',
    iosBundleId: 'com.travelpassport.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn-P55fEdwMg1uIasckywdS9MA8AJfdPM',
    appId: '1:794333114909:ios:544f69931d943a09774cf4',
    messagingSenderId: '794333114909',
    projectId: 'travel-passport-5cefb',
    storageBucket: 'travel-passport-5cefb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTrial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbzwjOq8kGTJPPSkrLxtF8dXP92IvNtcU',
    appId: '1:794333114909:web:391e9cf2eb36613b774cf4',
    messagingSenderId: '794333114909',
    projectId: 'travel-passport-5cefb',
    authDomain: 'travel-passport-5cefb.firebaseapp.com',
    storageBucket: 'travel-passport-5cefb.firebasestorage.app',
    measurementId: 'G-4NLV5PN1X8',
  );
}
